Pelahi/mpi updates
PawseySC/pawsey-containers pull request #10
Opened 2023-06-13 03:44 UTC by pelahi

Just updates to mpich container recipe (added metadata, added mpi4py since we need that too, added some more tests). Also added a recipe for building slurm in a container that works with Setonix and also spack (which is setup to build on top of the mpich image). The spack+mpi container is the critical one for groups that are really going to build a LOT of stuff in their container. Want to avoid the possibility of pulling in conflicting libraries (libcurl in particular) that cause issues when mounting libraries from Setonix into the container.

2023-06-13 08:10 UTC, marcodelapierre commented on .github/workflows/docker-image.yml
this is amazing, thanks Pascal!

2023-06-13 08:17 UTC, marcodelapierre requested changes
I think my only change suggestions are about the Spack dockerfile, see related comments.

I have left the Slurm one review to @ddeeptimahanti

2023-06-13 09:07 UTC, pelahi commented on spack/spack-mpich/buildspack.dockerfile
The main issue is then adding the mpi external for spack. But I'll figure out a clean way of doing this.

2023-06-19 23:06 UTC, AlexisEspinosaGayosso approved these changes
Seems fine to me.

2023-06-19 23:08 UTC, AlexisEspinosaGayosso approved these changes

2023-06-19 23:12 UTC, AlexisEspinosaGayosso approved these changes
All this looks fine for me. It would be nice to provide working examples on Setonix that we can access and test quickly rather than building the containers ourselves and think of ways for testing them.

2023-06-20 07:31 UTC, pelahi commented on spack/spack-mpich/buildspack.dockerfile
What I'll do is have two recipes, one that builds on the pawsey mpi and the other more generic.

2023-07-11 04:27 UTC, merged