Lustre-aware mpi recipe
PawseySC/pawsey-containers pull request #12
Opened 2023-08-23 03:35 UTC by pelahi

New recipe for lustre-aware mpi. Doing some further testing but initial tests are successful.

2023-08-23 06:36 UTC, marcodelapierre approved these changes
Tested build, could run and access container, Dockerfile looks good.

Only one request: can you post here what bind mounts are required (if any) in order to have a working combination of the container Lustre + Setonix Slurm ?

Thanks

2023-08-24 03:26 UTC, marcodelapierre commented
Thanks for adding this info here, good for future reference

2023-08-25 07:10 UTC, pelahi commented
@marcodelapierre @AlexisEspinosaGayosso , can you review. Having tested a parallel HDF5 read and write and also just MPI-IO I am happy with this recipe.

2023-08-28 07:14 UTC, marcodelapierre requested changes
This is amazing work, thank you @pelahi!

Successfully built the image, tested simple command outputs.

Please have a look at the few comments along the code.

2023-08-28 13:17 UTC, pelahi commented on mpi/lustrempich-base/buildlustrempich.dockerfile
> +RUN pip install mpi4py
same, now versioned

2023-08-28 13:20 UTC, marcodelapierre approved these changes

2023-08-28 13:27 UTC, merged