Build CUDA with lustre-aware mpich and lustre, CUDA version =12.5
PawseySC/pawsey-containers pull request #50
Opened 2024-06-19 05:06 UTC by Quleaf

Build CUDA with lustre-aware mpich and lustre, CUDA version =12.5.
his recepe includes CUDA 12.5.0 / lustre-aware MPICH 3.4.3 / Lustre 2.15.63 / OSU 6.2
Run bash build.sh

2024-06-19 14:05 UTC, pelahi requested changes
This seems like a good set of updates. My only  comment is that the buildhpcpython should have the associated build.sh to produce a container image with a name like `hpcpython_quantum`.

2024-06-24 08:38 UTC, pelahi requested changes

2024-06-26 04:32 UTC, Quleaf commented on applications/qiskit/buildqiskit-cuda.dockerfile
The reason is that only Ubuntu 23.04 is provided by quay.io/pawsey/hpcpython and quay.io/pawsey/pawsey /mpich-base. 
For qiskit on Mpich and CUDA cases, as 23.04 is not LTS and CUDA only provides 22.04 or 24.04 based image, I try to move the scripts to 22.04 for this compatibility reason. 
For ROCM cases, the ROCM image is based on quay.io/pawsey/rocm-mpich-base:rocm${ROCM_VERSION}-mpich3.4.3-ubuntu22 are used in the script.

2024-06-26 04:48 UTC, Quleaf commented
> This seems like a good set of updates. My only comment is that the buildhpcpython should have the associated build.sh to produce a container image with a name like `hpcpython_quantum`.

Done. Del the replicate files under python/hpc-python. Use application/qiskit for this purpose.

2024-06-27 06:31 UTC, pelahi approved these changes

2024-09-03 00:15 UTC, merged